//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Font48.Models.Controls
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelControls : DbContext
    {
        public ModelControls()
            : base("name=ModelControls")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TbActionType> TbActionTypes { get; set; }
        public virtual DbSet<TbAppType> TbAppTypes { get; set; }
        public virtual DbSet<TbControlType> TbControlTypes { get; set; }
        public virtual DbSet<TbTest> TbTests { get; set; }
        public virtual DbSet<TbControl> TbControls { get; set; }
        public virtual DbSet<TbAction> TbActions { get; set; }
    }
}
