//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Font48.Models.Controls
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbAction
    {
        public int Id { get; set; }
        public int TestId { get; set; }
        public int ActionTypeId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<double> FontSize { get; set; }
        public string FontName { get; set; }
    }
}
