//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Font48.Models.Controls
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbControl
    {
        public int Id { get; set; }
        public int ActionId { get; set; }
        public string ControlName { get; set; }
        public string ControlText { get; set; }
        public Nullable<int> ControlTypeId { get; set; }
        public Nullable<int> LocationX { get; set; }
        public Nullable<int> LocationY { get; set; }
        public Nullable<int> SizeX { get; set; }
        public Nullable<int> SizeY { get; set; }
        public Nullable<bool> IsAutoSize { get; set; }
    }
}
