//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Font48.Models.Controls
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbTest
    {
        public int Id { get; set; }
        public string TestName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<decimal> FontSize { get; set; }
        public Nullable<int> AppTypeId { get; set; }
    }
}
